<?php

namespace ML\FrontBundle\Repository;

/**
 * ReservationTypeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ReservationTypeRepository extends \Doctrine\ORM\EntityRepository
{
}
